id: P6E8AAC98
initial_creation_type: input
source_metadata:
  Title: Viśālāmalavatī Pramāṇasamuccayaṭīkā
  Editor: Horst Lasic, Helmut Krasser, Ernst Steinkellner
  Publisher: China Tibetology Publishing House
  Place of Publication: China
  Year: '2012'
  Viśālāmalavatī Pramāṇasamuccayaṭīkā:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:22:26.921533'
last_modified_at: '2022-03-08T17:22:26.921541'
